time-interval-minutes: 15
# or for a 1-hour interval:
# time-interval-minutes: 60

default-vouchers: 50

messages:
  voucher-received: "&aYou've received a voucher!"
  no-vouchers: "&cYou don't have any vouchers to redeem!"
  next-voucher: "&eNext voucher in: %minutes%m %seconds%s."
  redeemed: "&aYou've redeemed %count% voucher(s)!"

blacklisted-items:
  - BARRIER
  - BEDROCK
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - JIGSAW
  - DEBUG_STICK
  - COMMAND_BLOCK_MINECART
  - KNOWLEDGE_BOOK
  - WRITTEN_BOOK
  - END_PORTAL_FRAME
  - END_PORTAL
  - NETHER_PORTAL
