name: randomItemSpigot
version: '1.1'
main: de.jutechs.randomItemSpigot.Main
api-version: '1.21'
commands:
  redeem:
    description: Redeems a voucher for a random item.
    usage: /redeem
permissions:
  cantplaceblacklisted.bypass:
    description: Allows players to bypass block placement restrictions.
    default: false
